version: '3.8'

services:

  zapfhahn-db:
    image: mysql:8.2.0-oracle
    container_name: zapfhahn-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: zapfhahn
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"


  active-mq:
    image: apache/activemq-artemis:latest-alpine
    container_name: active-mq
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      - ARTEMIS_USER=mq
      - ARTEMIS_PASSWORD=mq

  eureka-server:
    image: zapfhahn/eureka
    container_name: eureka
    ports:
      - "8761:8761"
    build:
      context: ../eureka-server/
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    depends_on:
      - active-mq

  order-service:
    image: zapfhahn/order
    container_name: order
    ports:
      - "8081:8081"
    build:
      context: ../order-service
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/zapfhahn
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - active-mq
      - eureka-server
      - zapfhahn-db

  notification-service:
    image: zapfhahn/notification
    container_name: notification
    ports:
      - "8082:8082"
    build:
      context: ../notification-service
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/zapfhahn
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - active-mq
      - eureka-server
      - zapfhahn-db


