version: '3.8'

services:

  active-mq:
    image: apache/activemq-artemis:latest-alpine
    container_name: active-mq
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      - ARTEMIS_USER=mq
      - ARTEMIS_PASSWORD=mq
    networks:
      - zapfhahn-network

  eureka-server:
    image: zapfhahn/eureka
    container_name: eureka
    ports:
      - "8761:8761"
    build:
      context: ../eureka-server/
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    depends_on:
      - active-mq
    networks:
      - zapfhahn-network

  order-service:
    image: zapfhahn/order
    container_name: order
    ports:
      - "8081:8081"
    build:
      context: ../order-service
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://zapfhahn-db:3306/zapfhahn
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    depends_on:
      - active-mq
      - eureka-server
      - zapfhahn-db
    networks:
      - zapfhahn-network

  notification-service:
    image: zapfhahn/notification
    container_name: notification
    ports:
      - "8082:8082"
    build:
      context: ../notification-service
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://zapfhahn-db:3306/zapfhahn
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    depends_on:
      - active-mq
      - eureka-server
      - zapfhahn-db
    networks:
      - zapfhahn-network

  zapfhahn-db:
    image: mysql:8.0
    container_name: zapfhahn-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: zapfhahn
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - zapfhahn-network

  api-gateway:
    image: zapfhahn/apigateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - zapfhahn-network

networks:
  zapfhahn-network:
    driver: bridge

volumes:
  mysql-data:
